### PR TITLE
feature: powershell script for windows contributors

### PR DESCRIPTION
**Pull request by AntonioCardenas**
## 翻訳・修正

- [x] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md) に記載されたワークフローに従っています

### 備考

Hi i make this powershell scripts for contributors that use windows ,this works since windows 8ˆ and windows server ˆ2008  to actual versions like 10 or major versions of windows serve , i hope it helps

### CODE REVIEW

**Comment by lacolaco** [comment]
@AntonioCardenas Thank you for your patch. Could you rebase to the current master branch?

**Comment by AntonioCardenas** [comment]
@googlebot I fixed it.

**Comment by AntonioCardenas** [comment]
Hello @lacolaco I did the rebase, please tell me if it's okay, I'm something new doing rebase.

**Comment by lacolaco** [comment]
Sorry, I think this patch includes only a single commit but the current state seems mistaken.

**Comment by lacolaco** [comment]
I think fixing this git history is bother a little. Another easy way is checking out a new branch from the latest origin HEAD and create a new PR.

**Comment by AntonioCardenas** [comment]
Ok i will make a new pr

**Pull request closed without merging**
